language: rust

cache: cargo

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      script:
        - export CXX=g++-7
        - export CC=gcc-7

    # - os: osx
