[package]
name = "simdjson-rust"
version = "0.1.0"
authors = ["SunDoge <384813529@qq.com>"]
edition = "2018"

# [dependencies]
# simdjson-sys = {path="simdjson-sys"}

# [workspace]
# members = ["simdjson-sys"]


[dependencies]
cxx = "0.3"
thiserror = "1.0"
anyhow = "1.0"

[build-dependencies]
cxx-build = "0.3"
