[package]
name = "simdjson-sys"
version = "0.1.0"
authors = ["SunDoge <384813529@qq.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.51.0"
cmake = "0.1.42"

[features]
default = []
disable_avx = []